___

___
# Text Generation with Neural Networks


In [ ]:
# GOOGLE COLLAB USERS ONLY
%tensorflow_version 2.x

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
# IGNORE THE CONTENT OF THIS CELL
# tf.compat.v1.disable_eager_execution()

In [2]:
tf.__version__

'2.4.1'

## Step 1: The Data



In [3]:
path_to_file = 'fiction_bookshelf.txt'

In [4]:
text = open(path_to_file, 'r').read()

In [5]:
print(text[:500])


BOOK ONE
THE COMING OF THE MARTIANS



I.
THE EVE OF THE WAR.

No one would have believed in the last years of the nineteenth century
that this world was being watched keenly and closely by intelligences
greater than man’s and yet as mortal as his own; that as men busied
themselves about their various concerns they were scrutinised and
studied, perhaps almost as narrowly as a man with a microscope might
scrutinise the transient creatures that swarm and multiply in a drop of
water. With infinite


### Understanding unique characters

In [6]:
# The unique characters in the file
vocab = sorted(set(text))
print(vocab)
len(vocab)

['\n', ' ', '!', '"', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '}', '£', '°', 'â', 'ä', 'æ', 'ç', 'è', 'é', 'ë', 'ó', 'ô', 'ü', 'œ', 'θ', '—', '‘', '’', '“', '”', '…', '′', '″']


112

## Step 2: Text Processing

We know a neural network can't take in the raw string data, we need to assign numbers to each character.So we create two dictionaries that can go from numeric index to character and character to numeric index.

### Text Vectorization


In [7]:
char_to_ind = {u:i for i, u in enumerate(vocab)}

In [8]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '$': 4,
 '%': 5,
 '&': 6,
 "'": 7,
 '(': 8,
 ')': 9,
 '*': 10,
 '+': 11,
 ',': 12,
 '-': 13,
 '.': 14,
 '/': 15,
 '0': 16,
 '1': 17,
 '2': 18,
 '3': 19,
 '4': 20,
 '5': 21,
 '6': 22,
 '7': 23,
 '8': 24,
 '9': 25,
 ':': 26,
 ';': 27,
 '<': 28,
 '=': 29,
 '>': 30,
 '?': 31,
 'A': 32,
 'B': 33,
 'C': 34,
 'D': 35,
 'E': 36,
 'F': 37,
 'G': 38,
 'H': 39,
 'I': 40,
 'J': 41,
 'K': 42,
 'L': 43,
 'M': 44,
 'N': 45,
 'O': 46,
 'P': 47,
 'Q': 48,
 'R': 49,
 'S': 50,
 'T': 51,
 'U': 52,
 'V': 53,
 'W': 54,
 'X': 55,
 'Y': 56,
 'Z': 57,
 '[': 58,
 ']': 59,
 '_': 60,
 '`': 61,
 'a': 62,
 'b': 63,
 'c': 64,
 'd': 65,
 'e': 66,
 'f': 67,
 'g': 68,
 'h': 69,
 'i': 70,
 'j': 71,
 'k': 72,
 'l': 73,
 'm': 74,
 'n': 75,
 'o': 76,
 'p': 77,
 'q': 78,
 'r': 79,
 's': 80,
 't': 81,
 'u': 82,
 'v': 83,
 'w': 84,
 'x': 85,
 'y': 86,
 'z': 87,
 '{': 88,
 '}': 89,
 '£': 90,
 '°': 91,
 'â': 92,
 'ä': 93,
 'æ': 94,
 'ç': 95,
 'è': 96,
 'é': 97,
 'ë': 98,
 'ó': 99,
 'ô': 100

In [9]:
ind_to_char = np.array(vocab)

In [10]:
ind_to_char

array(['\n', ' ', '!', '"', '$', '%', '&', "'", '(', ')', '*', '+', ',',
       '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ':', ';', '<', '=', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G',
       'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
       'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c',
       'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p',
       'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '}', '£',
       '°', 'â', 'ä', 'æ', 'ç', 'è', 'é', 'ë', 'ó', 'ô', 'ü', 'œ', 'θ',
       '—', '‘', '’', '“', '”', '…', '′', '″'], dtype='<U1')

In [11]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [12]:
encoded_text

array([ 0, 33, 46, ...,  0,  0,  0])

We now have a mapping we can use to go back and forth from characters to numerics.

In [13]:
sample = text[:20]
sample

'\nBOOK ONE\nTHE COMING'

In [14]:
encoded_text[:20]

array([ 0, 33, 46, 46, 42,  1, 46, 45, 36,  0, 51, 39, 36,  1, 34, 46, 44,
       40, 45, 38])

## Step 3: Creating Batches


Overall what we are trying to achieve is to have the model predict the next highest probability character given a historical sequence of characters. Its up to us (the user) to choose how long that historic sequence. Too short a sequence and we don't have enough information (e.g. given the letter "a" , what is the next character) , too long a sequence and training will take too long and most likely overfit to sequence characters that are irrelevant to characters farther out. While there is no correct sequence length choice, we should consider the text itself, how long normal phrases are in it, and a reasonable idea of what characters/words are relevant to each other.

In [15]:
print(text[:500])


BOOK ONE
THE COMING OF THE MARTIANS



I.
THE EVE OF THE WAR.

No one would have believed in the last years of the nineteenth century
that this world was being watched keenly and closely by intelligences
greater than man’s and yet as mortal as his own; that as men busied
themselves about their various concerns they were scrutinised and
studied, perhaps almost as narrowly as a man with a microscope might
scrutinise the transient creatures that swarm and multiply in a drop of
water. With infinite


In [16]:
line = "From fairest creatures we desire increase"

In [17]:
len(line)

41

In [18]:
part_stanza = """From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,"""

In [19]:
len(part_stanza)

131

### Training Sequences

We can use the `tf.data.Dataset.from_tensor_slices` function to convert a text vector into a stream of character indices.

In [20]:
seq_len = 120

In [21]:
total_num_seq = len(text)//(seq_len+1)

In [22]:
total_num_seq

59360

In [23]:
# Create Training Sequences
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

for i in char_dataset.take(500):
     print(ind_to_char[i.numpy()])



B
O
O
K
 
O
N
E


T
H
E
 
C
O
M
I
N
G
 
O
F
 
T
H
E
 
M
A
R
T
I
A
N
S








I
.


T
H
E
 
E
V
E
 
O
F
 
T
H
E
 
W
A
R
.




N
o
 
o
n
e
 
w
o
u
l
d
 
h
a
v
e
 
b
e
l
i
e
v
e
d
 
i
n
 
t
h
e
 
l
a
s
t
 
y
e
a
r
s
 
o
f
 
t
h
e
 
n
i
n
e
t
e
e
n
t
h
 
c
e
n
t
u
r
y


t
h
a
t
 
t
h
i
s
 
w
o
r
l
d
 
w
a
s
 
b
e
i
n
g
 
w
a
t
c
h
e
d
 
k
e
e
n
l
y
 
a
n
d
 
c
l
o
s
e
l
y
 
b
y
 
i
n
t
e
l
l
i
g
e
n
c
e
s


g
r
e
a
t
e
r
 
t
h
a
n
 
m
a
n
’
s
 
a
n
d
 
y
e
t
 
a
s
 
m
o
r
t
a
l
 
a
s
 
h
i
s
 
o
w
n
;
 
t
h
a
t
 
a
s
 
m
e
n
 
b
u
s
i
e
d


t
h
e
m
s
e
l
v
e
s
 
a
b
o
u
t
 
t
h
e
i
r
 
v
a
r
i
o
u
s
 
c
o
n
c
e
r
n
s
 
t
h
e
y
 
w
e
r
e
 
s
c
r
u
t
i
n
i
s
e
d
 
a
n
d


s
t
u
d
i
e
d
,
 
p
e
r
h
a
p
s
 
a
l
m
o
s
t
 
a
s
 
n
a
r
r
o
w
l
y
 
a
s
 
a
 
m
a
n
 
w
i
t
h
 
a
 
m
i
c
r
o
s
c
o
p
e
 
m
i
g
h
t


s
c
r
u
t
i
n
i
s
e
 
t
h
e
 
t
r
a
n
s
i
e
n
t
 
c
r
e
a
t
u
r
e
s
 
t
h
a
t
 
s
w
a
r
m
 
a
n
d
 
m
u
l
t
i
p
l
y
 
i
n
 
a
 
d
r
o
p
 
o
f


w
a
t
e
r
.
 
W
i
t
h
 
i
n
f
i
n
i
t
e


The **batch** method converts these individual character calls into sequences we can feed in as a batch. We use seq_len+1 because of zero indexing. Here is what drop_remainder means:

drop_remainder: (Optional.) A `tf.bool` scalar `tf.Tensor`, representing
    whether the last batch should be dropped in the case it has fewer than
    `batch_size` elements; the default behavior is not to drop the smaller
    batch.



In [24]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

Now that we have our sequences, we will perform the following steps for each one to create our target text sequences:

1. Grab the input text sequence
2. Assign the target text sequence as the input text sequence shifted by one step forward
3. Group them together as a tuple

In [25]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [26]:
dataset = sequences.map(create_seq_targets)

In [27]:
for input_txt, target_txt in  dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 0 33 46 46 42  1 46 45 36  0 51 39 36  1 34 46 44 40 45 38  1 46 37  1
 51 39 36  1 44 32 49 51 40 32 45 50  0  0  0  0 40 14  0 51 39 36  1 36
 53 36  1 46 37  1 51 39 36  1 54 32 49 14  0  0 45 76  1 76 75 66  1 84
 76 82 73 65  1 69 62 83 66  1 63 66 73 70 66 83 66 65  1 70 75  1 81 69
 66  1 73 62 80 81  1 86 66 62 79 80  1 76 67  1 81 69 66  1 75 70 75 66]

BOOK ONE
THE COMING OF THE MARTIANS



I.
THE EVE OF THE WAR.

No one would have believed in the last years of the nine


[33 46 46 42  1 46 45 36  0 51 39 36  1 34 46 44 40 45 38  1 46 37  1 51
 39 36  1 44 32 49 51 40 32 45 50  0  0  0  0 40 14  0 51 39 36  1 36 53
 36  1 46 37  1 51 39 36  1 54 32 49 14  0  0 45 76  1 76 75 66  1 84 76
 82 73 65  1 69 62 83 66  1 63 66 73 70 66 83 66 65  1 70 75  1 81 69 66
  1 73 62 80 81  1 86 66 62 79 80  1 76 67  1 81 69 66  1 75 70 75 66 81]
BOOK ONE
THE COMING OF THE MARTIANS



I.
THE EVE OF THE WAR.

No one would have believed in the last years of the ninet


### Generating training batches


In [28]:
# Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [29]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

## Step 4: Creating the Model

We will use an LSTM based model with a few extra features, including an embedding layer to start off with and **two** LSTM layers. We based this model architecture off the [DeepMoji](https://deepmoji.mit.edu/) and the original source code can be found [here](https://github.com/bfelbo/DeepMoji).

The embedding layer will serve as the input layer, which essentially creates a lookup table that maps the numbers indices of each character to a vector with "embedding dim" number of dimensions. As you can imagine, the larger this embedding size, the more complex the training. This is similar to the idea behind word2vec, where words are mapped to some n-dimensional space. Embedding before feeding straight into the LSTM usually leads to more realisitic results.

In [30]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embed_dim = 64

# Number of RNN units
rnn_neurons = 1026

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

### Setting up Loss Function


In [32]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [33]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module tensorflow.python.keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    Args:
      y_true: Ground truth values.
      y_pred: The predicted values.
      from_logits: Whether `y_pred` is expected to be a logits tensor. By default,
        we assume that `y_pred` encodes a probability distribution.
      axis: (Optional) Defaults to -1. The dimension along which the entropy is
        computed.
    
    Returns:
      Sparse categorical crossentropy loss value.



In [34]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [35]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss) 
    return model

In [36]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           7168      
_________________________________________________________________
gru (GRU)                    (128, None, 1026)         3361176   
_________________________________________________________________
dense (Dense)                (128, None, 112)          115024    
Total params: 3,483,368
Trainable params: 3,483,368
Non-trainable params: 0
_________________________________________________________________


## Step 5: Training the model




In [38]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Display the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")


(128, 120, 112)  <=== (batch_size, sequence_length, vocab_size)


In [39]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 112), dtype=float32, numpy=
array([[[-4.6868906e-03,  1.7249676e-04,  2.6533869e-03, ...,
         -2.9775954e-03,  1.3485337e-03, -1.8939876e-03],
        [-8.1245145e-03, -7.3904484e-03,  6.3081165e-03, ...,
         -1.2581771e-03,  6.1745932e-03, -2.9967452e-04],
        [-5.4868604e-03, -3.4556896e-03,  8.6797751e-04, ...,
         -6.1116945e-03,  7.1613132e-03, -1.1668691e-03],
        ...,
        [ 1.9273338e-03,  1.5813260e-03,  2.3270492e-03, ...,
          2.7080327e-05,  4.9898778e-03,  1.8972355e-04],
        [ 3.3142904e-03, -5.3595467e-03, -5.7284860e-03, ...,
          1.6457392e-03,  6.8292459e-03,  7.4292156e-03],
        [ 1.8615928e-03, -1.5379163e-03, -3.8789979e-03, ...,
         -4.3346495e-03,  9.8459898e-03, -1.8586889e-04]],

       [[-1.7119254e-03,  2.2339786e-03,  2.4650595e-03, ...,
         -1.5465171e-03, -3.0206128e-03,  3.7206125e-03],
        [ 1.3408975e-03,  4.3012253e-03, -1.0392750e-04, ...,
         -3.8454540e-03, -

In [40]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [41]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[ 45],
       [ 80],
       [  9],
       [ 92],
       [ 37],
       [ 13],
       [ 68],
       [ 37],
       [ 86],
       [ 94],
       [ 81],
       [ 99],
       [ 79],
       [ 45],
       [ 75],
       [ 84],
       [ 64],
       [ 25],
       [ 55],
       [ 55],
       [107],
       [102],
       [ 82],
       [ 98],
       [ 44],
       [ 59],
       [ 64],
       [ 21],
       [  0],
       [106],
       [ 94],
       [ 85],
       [  3],
       [ 48],
       [ 65],
       [ 72],
       [ 86],
       [ 81],
       [ 49],
       [  6],
       [ 64],
       [ 79],
       [  3],
       [106],
       [ 26],
       [ 55],
       [ 31],
       [ 10],
       [ 86],
       [ 78],
       [ 92],
       [105],
       [ 95],
       [  2],
       [ 74],
       [ 32],
       [ 14],
       [  0],
       [ 98],
       [ 97],
       [  2],
       [ 37],
       [ 63],
       [ 28],
       [109],
       [ 99],
       [ 68],
       [ 40],


In [42]:
# Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [43]:
sampled_indices

array([ 45,  80,   9,  92,  37,  13,  68,  37,  86,  94,  81,  99,  79,
        45,  75,  84,  64,  25,  55,  55, 107, 102,  82,  98,  44,  59,
        64,  21,   0, 106,  94,  85,   3,  48,  65,  72,  86,  81,  49,
         6,  64,  79,   3, 106,  26,  55,  31,  10,  86,  78,  92, 105,
        95,   2,  74,  32,  14,   0,  98,  97,   2,  37,  63,  28, 109,
        99,  68,  40,  55,  21,  23,  13,  69,  13,  67,  14,   2,  27,
        22,  38,  13,   2,   1,  85,  58,  79,   1,  11,  65,   0,  35,
        56,  94,  43,  56,  68,  94, 111,  78,  16,  82,  89, 104,  75,
        65,  12, 102,  96,  39,  19,  96,  96,  80,  13,  81,  16,   5,
       105,  12,  11])

In [44]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))


Given the input seq: 

s, and no signs of the Martians. I
encountered a couple of hungry-looking dogs, but both hurried
circuitously away from 


Next Char Predictions: 

Ns)âF-gFyætórNnwc9XX“œuëM]c5
’æx"QdkytR&cr"’:X?*yqâ‘ç!mA.
ëé!Fb<…ógIX57-h-f.!;6G-! x[r +d
DYæLYgæ″q0u}—nd,œèH3èès-t0%‘,+


In [45]:
epochs = 30

In [46]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
463/463 [==============================] - 124s 261ms/step - loss: 2.9181
Epoch 2/30
463/463 [==============================] - 123s 262ms/step - loss: 1.7584
Epoch 3/30
463/463 [==============================] - 122s 261ms/step - loss: 1.4600
Epoch 4/30
463/463 [==============================] - 123s 262ms/step - loss: 1.3546
Epoch 5/30
463/463 [==============================] - 123s 262ms/step - loss: 1.3010
Epoch 6/30
463/463 [==============================] - 123s 262ms/step - loss: 1.2660
Epoch 7/30
463/463 [==============================] - 123s 261ms/step - loss: 1.2405
Epoch 8/30
463/463 [==============================] - 123s 262ms/step - loss: 1.2192
Epoch 9/30
463/463 [==============================] - 122s 261ms/step - loss: 1.2012
Epoch 10/30
463/463 [==============================] - 123s 262ms/step - loss: 1.1869
Epoch 11/30
463/463 [==============================] - 123s 262ms/step - loss: 1.1727
Epoch 12/30
463/463 [==============================] - 122s 261

## Step 6: Generating text


In [47]:
model.save('fiction_gen.h5') 

In [48]:
from tensorflow.keras.models import load_model

In [49]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

model.load_weights('fiction_gen.h5')

model.build(tf.TensorShape([1, None]))


In [ ]:
model.summary()

In [51]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters. Similar to our work in the RNN
  time series problems.
  '''

  # Number of characters to generate
  num_generate = gen_size

  # Vecotrizing starting seed text
  input_eval = [char_to_ind[s] for s in start_seed]

  # Expand to match batch format shape
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty list to hold resulting generated text
  text_generated = []

  # Temperature effects randomness in our resulting text
  # The term is derived from entropy/thermodynamics.
  # The temperature is used to effect probability of next characters.
  # Higher probability == lesss surprising/ more expected
  # Lower temperature == more surprising / less expected
 
  temperature = temp

  # Here batch size == 1
  model.reset_states()

  for i in range(num_generate):

      # Generate Predictions
      predictions = model(input_eval)

      # Remove the batch shape dimension
      predictions = tf.squeeze(predictions, 0)

      # Use a cateogircal disitribution to select the next character
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # Pass the predicted charracter for the next input
      input_eval = tf.expand_dims([predicted_id], 0)

      # Transform back to character letter
      text_generated.append(ind_to_char[predicted_id])

  return (start_seed + ''.join(text_generated))

In [52]:
print(generate_text(model,"Time",gen_size=1000))

Timed Uncle _vixe_!

Their full glowing motion had caused them for the land it was easy to set out. eremen,
or bare; he burned all these scrapus of Helium.  There was the
composition of his motive return to the door, where the
beletion of my first huge die Pencroft was just as good as the girl cut off two
ears and of course.  A young friend, in the court it was all else
had gone before I give an acid small.

His name.

Second maneuvered, and she also recourse to the extent of
Roger's OtKE "JY There, the, Barbicane, put in cases and white beams to
his teeth. The sky, final restments, start
silky is
connected with his bare face, and dropped their laving and squealing, radiation. Not his
withs justly pointed to a speed of ameler wires with all
my guarding bed from him. He smushed over it smoor; a March
Trask.  "Far off, one vast district people were encigning.

"Just as you please, pisited around his odd; neither Port of North Careou!"

[1] and now in the mountain! The possibility ws up t