___

___
# Text Generation with Neural Networks


In [85]:
# GOOGLE COLLAB USERS ONLY
%tensorflow_version 2.x

In [86]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [87]:
# IGNORE THE CONTENT OF THIS CELL
# tf.compat.v1.disable_eager_execution()

In [88]:
tf.__version__

'2.4.1'

## Step 1: The Data



In [89]:
path_to_file = 'fiction_bookshelf.txt'

In [90]:
text = open(path_to_file, 'r').read()

In [91]:
print(text[:500])


BOOK ONE
THE COMING OF THE MARTIANS



I.
THE EVE OF THE WAR.

No one would have believed in the last years of the nineteenth century
that this world was being watched keenly and closely by intelligences
greater than man’s and yet as mortal as his own; that as men busied
themselves about their various concerns they were scrutinised and
studied, perhaps almost as narrowly as a man with a microscope might
scrutinise the transient creatures that swarm and multiply in a drop of
water. With infinite


### Understanding unique characters

In [92]:
#NEW
text2=""
specials=['"',"'","{","}","[","]","_",",",".","!","$","\n"," "]
for i in text:
  if i in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" or i in specials:
    text2=text2+i
text=text2

In [93]:
text[:500]

'\nBOOK ONE\nTHE COMING OF THE MARTIANS\n\n\n\nI.\nTHE EVE OF THE WAR.\n\nNo one would have believed in the last years of the nineteenth century\nthat this world was being watched keenly and closely by intelligences\ngreater than mans and yet as mortal as his own that as men busied\nthemselves about their various concerns they were scrutinised and\nstudied, perhaps almost as narrowly as a man with a microscope might\nscrutinise the transient creatures that swarm and multiply in a drop of\nwater. With infinite c'

In [94]:
# The unique characters in the file
vocab = sorted(set(text))
# new

# ***
print(vocab)
len(vocab)

['\n', ' ', '!', '"', '$', "'", ',', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '}']


75

## Step 2: Text Processing

We know a neural network can't take in the raw string data, we need to assign numbers to each character.So we create two dictionaries that can go from numeric index to character and character to numeric index.

### Text Vectorization


In [95]:
char_to_ind = {u:i for i, u in enumerate(vocab)}

In [96]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '$': 4,
 "'": 5,
 ',': 6,
 '.': 7,
 '0': 8,
 '1': 9,
 '2': 10,
 '3': 11,
 '4': 12,
 '5': 13,
 '6': 14,
 '7': 15,
 '8': 16,
 '9': 17,
 'A': 18,
 'B': 19,
 'C': 20,
 'D': 21,
 'E': 22,
 'F': 23,
 'G': 24,
 'H': 25,
 'I': 26,
 'J': 27,
 'K': 28,
 'L': 29,
 'M': 30,
 'N': 31,
 'O': 32,
 'P': 33,
 'Q': 34,
 'R': 35,
 'S': 36,
 'T': 37,
 'U': 38,
 'V': 39,
 'W': 40,
 'X': 41,
 'Y': 42,
 'Z': 43,
 '[': 44,
 ']': 45,
 '_': 46,
 'a': 47,
 'b': 48,
 'c': 49,
 'd': 50,
 'e': 51,
 'f': 52,
 'g': 53,
 'h': 54,
 'i': 55,
 'j': 56,
 'k': 57,
 'l': 58,
 'm': 59,
 'n': 60,
 'o': 61,
 'p': 62,
 'q': 63,
 'r': 64,
 's': 65,
 't': 66,
 'u': 67,
 'v': 68,
 'w': 69,
 'x': 70,
 'y': 71,
 'z': 72,
 '{': 73,
 '}': 74}

In [97]:
ind_to_char = np.array(vocab)

In [98]:
ind_to_char

array(['\n', ' ', '!', '"', '$', "'", ',', '.', '0', '1', '2', '3', '4',
       '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
       'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U',
       'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e',
       'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r',
       's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '}'], dtype='<U1')

In [99]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [100]:
encoded_text

array([ 0, 19, 32, ...,  0,  0,  0])

We now have a mapping we can use to go back and forth from characters to numerics.

In [101]:
sample = text[:20]
sample

'\nBOOK ONE\nTHE COMING'

In [102]:
encoded_text[:20]

array([ 0, 19, 32, 32, 28,  1, 32, 31, 22,  0, 37, 25, 22,  1, 20, 32, 30,
       26, 31, 24])

## Step 3: Creating Batches


Overall what we are trying to achieve is to have the model predict the next highest probability character given a historical sequence of characters. Its up to us (the user) to choose how long that historic sequence. Too short a sequence and we don't have enough information (e.g. given the letter "a" , what is the next character) , too long a sequence and training will take too long and most likely overfit to sequence characters that are irrelevant to characters farther out. While there is no correct sequence length choice, we should consider the text itself, how long normal phrases are in it, and a reasonable idea of what characters/words are relevant to each other.

In [103]:
print(text[:500])


BOOK ONE
THE COMING OF THE MARTIANS



I.
THE EVE OF THE WAR.

No one would have believed in the last years of the nineteenth century
that this world was being watched keenly and closely by intelligences
greater than mans and yet as mortal as his own that as men busied
themselves about their various concerns they were scrutinised and
studied, perhaps almost as narrowly as a man with a microscope might
scrutinise the transient creatures that swarm and multiply in a drop of
water. With infinite c


In [104]:
line = "From fairest creatures we desire increase"

In [105]:
len(line)

41

In [106]:
part_stanza = """From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,"""

In [107]:
len(part_stanza)

131

### Training Sequences

We can use the `tf.data.Dataset.from_tensor_slices` function to convert a text vector into a stream of character indices.

In [108]:
seq_len = 120

In [109]:
total_num_seq = len(text)//(seq_len+1)

In [110]:
total_num_seq

58929

In [111]:
# Create Training Sequences
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

for i in char_dataset.take(500):
     print(ind_to_char[i.numpy()])



B
O
O
K
 
O
N
E


T
H
E
 
C
O
M
I
N
G
 
O
F
 
T
H
E
 
M
A
R
T
I
A
N
S








I
.


T
H
E
 
E
V
E
 
O
F
 
T
H
E
 
W
A
R
.




N
o
 
o
n
e
 
w
o
u
l
d
 
h
a
v
e
 
b
e
l
i
e
v
e
d
 
i
n
 
t
h
e
 
l
a
s
t
 
y
e
a
r
s
 
o
f
 
t
h
e
 
n
i
n
e
t
e
e
n
t
h
 
c
e
n
t
u
r
y


t
h
a
t
 
t
h
i
s
 
w
o
r
l
d
 
w
a
s
 
b
e
i
n
g
 
w
a
t
c
h
e
d
 
k
e
e
n
l
y
 
a
n
d
 
c
l
o
s
e
l
y
 
b
y
 
i
n
t
e
l
l
i
g
e
n
c
e
s


g
r
e
a
t
e
r
 
t
h
a
n
 
m
a
n
s
 
a
n
d
 
y
e
t
 
a
s
 
m
o
r
t
a
l
 
a
s
 
h
i
s
 
o
w
n
 
t
h
a
t
 
a
s
 
m
e
n
 
b
u
s
i
e
d


t
h
e
m
s
e
l
v
e
s
 
a
b
o
u
t
 
t
h
e
i
r
 
v
a
r
i
o
u
s
 
c
o
n
c
e
r
n
s
 
t
h
e
y
 
w
e
r
e
 
s
c
r
u
t
i
n
i
s
e
d
 
a
n
d


s
t
u
d
i
e
d
,
 
p
e
r
h
a
p
s
 
a
l
m
o
s
t
 
a
s
 
n
a
r
r
o
w
l
y
 
a
s
 
a
 
m
a
n
 
w
i
t
h
 
a
 
m
i
c
r
o
s
c
o
p
e
 
m
i
g
h
t


s
c
r
u
t
i
n
i
s
e
 
t
h
e
 
t
r
a
n
s
i
e
n
t
 
c
r
e
a
t
u
r
e
s
 
t
h
a
t
 
s
w
a
r
m
 
a
n
d
 
m
u
l
t
i
p
l
y
 
i
n
 
a
 
d
r
o
p
 
o
f


w
a
t
e
r
.
 
W
i
t
h
 
i
n
f
i
n
i
t
e
 
c


The **batch** method converts these individual character calls into sequences we can feed in as a batch. We use seq_len+1 because of zero indexing. Here is what drop_remainder means:

drop_remainder: (Optional.) A `tf.bool` scalar `tf.Tensor`, representing
    whether the last batch should be dropped in the case it has fewer than
    `batch_size` elements; the default behavior is not to drop the smaller
    batch.



In [112]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

Now that we have our sequences, we will perform the following steps for each one to create our target text sequences:

1. Grab the input text sequence
2. Assign the target text sequence as the input text sequence shifted by one step forward
3. Group them together as a tuple

In [113]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [114]:
dataset = sequences.map(create_seq_targets)

In [115]:
for input_txt, target_txt in  dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 0 19 32 32 28  1 32 31 22  0 37 25 22  1 20 32 30 26 31 24  1 32 23  1
 37 25 22  1 30 18 35 37 26 18 31 36  0  0  0  0 26  7  0 37 25 22  1 22
 39 22  1 32 23  1 37 25 22  1 40 18 35  7  0  0 31 61  1 61 60 51  1 69
 61 67 58 50  1 54 47 68 51  1 48 51 58 55 51 68 51 50  1 55 60  1 66 54
 51  1 58 47 65 66  1 71 51 47 64 65  1 61 52  1 66 54 51  1 60 55 60 51]

BOOK ONE
THE COMING OF THE MARTIANS



I.
THE EVE OF THE WAR.

No one would have believed in the last years of the nine


[19 32 32 28  1 32 31 22  0 37 25 22  1 20 32 30 26 31 24  1 32 23  1 37
 25 22  1 30 18 35 37 26 18 31 36  0  0  0  0 26  7  0 37 25 22  1 22 39
 22  1 32 23  1 37 25 22  1 40 18 35  7  0  0 31 61  1 61 60 51  1 69 61
 67 58 50  1 54 47 68 51  1 48 51 58 55 51 68 51 50  1 55 60  1 66 54 51
  1 58 47 65 66  1 71 51 47 64 65  1 61 52  1 66 54 51  1 60 55 60 51 66]
BOOK ONE
THE COMING OF THE MARTIANS



I.
THE EVE OF THE WAR.

No one would have believed in the last years of the ninet


### Generating training batches


In [116]:
# Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [117]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

## Step 4: Creating the Model

We will use an LSTM based model with a few extra features, including an embedding layer to start off with and **two** LSTM layers. We based this model architecture off the [DeepMoji](https://deepmoji.mit.edu/) and the original source code can be found [here](https://github.com/bfelbo/DeepMoji).

The embedding layer will serve as the input layer, which essentially creates a lookup table that maps the numbers indices of each character to a vector with "embedding dim" number of dimensions. As you can imagine, the larger this embedding size, the more complex the training. This is similar to the idea behind word2vec, where words are mapped to some n-dimensional space. Embedding before feeding straight into the LSTM usually leads to more realisitic results.

In [118]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embed_dim = 64

# Number of RNN units
rnn_neurons = 1026

In [119]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

### Setting up Loss Function


In [120]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [121]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module tensorflow.python.keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    Args:
      y_true: Ground truth values.
      y_pred: The predicted values.
      from_logits: Whether `y_pred` is expected to be a logits tensor. By default,
        we assume that `y_pred` encodes a probability distribution.
      axis: (Optional) Defaults to -1. The dimension along which the entropy is
        computed.
    
    Returns:
      Sparse categorical crossentropy loss value.



In [122]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [123]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss) 
    return model

In [124]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [125]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (128, None, 64)           4800      
_________________________________________________________________
gru_4 (GRU)                  (128, None, 1026)         3361176   
_________________________________________________________________
dense_4 (Dense)              (128, None, 75)           77025     
Total params: 3,443,001
Trainable params: 3,443,001
Non-trainable params: 0
_________________________________________________________________


## Step 5: Training the model




In [126]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Display the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")


(128, 120, 75)  <=== (batch_size, sequence_length, vocab_size)


In [127]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 75), dtype=float32, numpy=
array([[[ 1.05990935e-03, -4.61204583e-03,  1.57702831e-03, ...,
         -3.68429627e-03,  8.26382078e-03, -6.01013890e-04],
        [ 6.62855431e-03, -3.83498822e-03, -6.79346034e-03, ...,
          9.04543558e-05, -1.72366516e-03,  6.24943757e-04],
        [-7.06152059e-06, -6.18229806e-03, -9.45388712e-03, ...,
         -3.07954778e-03, -2.73719011e-03,  2.81542679e-03],
        ...,
        [-2.18794681e-03, -6.27359049e-03, -5.81811834e-03, ...,
         -5.01669198e-03, -5.72535675e-03,  1.62856234e-03],
        [ 3.24252667e-03,  1.22581923e-03, -5.30428160e-03, ...,
         -3.99071630e-03, -4.50633094e-03,  4.40498162e-03],
        [ 4.59335651e-03,  2.86829146e-03, -2.14288686e-03, ...,
          3.89062427e-03, -3.81574966e-04, -1.07114646e-03]],

       [[ 2.57580681e-03,  2.18334724e-04, -3.62313958e-03, ...,
          3.80185153e-03,  1.38895353e-04, -3.02373664e-03],
        [ 5.23484778e-03, -2.89282249e-03,  3.2

In [128]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [129]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[20],
       [68],
       [20],
       [49],
       [45],
       [29],
       [13],
       [22],
       [72],
       [10],
       [32],
       [56],
       [ 3],
       [ 8],
       [ 3],
       [16],
       [16],
       [65],
       [64],
       [53],
       [ 6],
       [19],
       [35],
       [46],
       [13],
       [10],
       [ 2],
       [21],
       [60],
       [69],
       [10],
       [10],
       [69],
       [59],
       [65],
       [38],
       [ 2],
       [10],
       [69],
       [ 8],
       [15],
       [73],
       [42],
       [67],
       [48],
       [34],
       [14],
       [62],
       [69],
       [65],
       [28],
       [32],
       [30],
       [ 3],
       [23],
       [34],
       [47],
       [36],
       [ 3],
       [ 0],
       [37],
       [29],
       [20],
       [67],
       [28],
       [ 3],
       [ 9],
       [27],
       [12],
       [55],
       [ 4],
       [28],
       [72],
   

In [130]:
# Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [131]:
sampled_indices

array([20, 68, 20, 49, 45, 29, 13, 22, 72, 10, 32, 56,  3,  8,  3, 16, 16,
       65, 64, 53,  6, 19, 35, 46, 13, 10,  2, 21, 60, 69, 10, 10, 69, 59,
       65, 38,  2, 10, 69,  8, 15, 73, 42, 67, 48, 34, 14, 62, 69, 65, 28,
       32, 30,  3, 23, 34, 47, 36,  3,  0, 37, 29, 20, 67, 28,  3,  9, 27,
       12, 55,  4, 28, 72, 73, 64, 48, 40, 35, 15, 11, 27, 47, 42, 72, 50,
       17, 66, 67, 43, 40, 62, 48, 59, 60, 45, 23, 26, 38, 17, 12, 26, 62,
       58, 35, 25, 35, 46, 65, 40, 33, 27,  7,  8, 68,  7, 52, 45, 17, 44,
       70])

In [132]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))


Given the input seq: 

ne day, out by Wandsworth, picking
houses to pieces and routing among the wreckage. But they wont keep on
doing that. So


Next Char Predictions: 

CvCc]L5Ez2Oj"0"88srg,BR_52!Dnw22wmsU!2w07{YubQ6pwsKOM"FQaS"
TLCuK"1J4i$Kz{rbWR73JaYzd9tuZWpbmn]FIU94IplRHR_sWPJ.0v.f]9[x


In [133]:
epochs = 30

In [134]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
460/460 [==============================] - 73s 154ms/step - loss: 2.8590
Epoch 2/30
460/460 [==============================] - 74s 159ms/step - loss: 1.7155
Epoch 3/30
460/460 [==============================] - 74s 159ms/step - loss: 1.4467
Epoch 4/30
460/460 [==============================] - 74s 158ms/step - loss: 1.3472
Epoch 5/30
460/460 [==============================] - 73s 157ms/step - loss: 1.2963
Epoch 6/30
460/460 [==============================] - 74s 159ms/step - loss: 1.2625
Epoch 7/30
460/460 [==============================] - 74s 158ms/step - loss: 1.2364
Epoch 8/30
460/460 [==============================] - 74s 159ms/step - loss: 1.2162
Epoch 9/30
460/460 [==============================] - 75s 160ms/step - loss: 1.1987
Epoch 10/30
460/460 [==============================] - 75s 160ms/step - loss: 1.1838
Epoch 11/30
460/460 [==============================] - 74s 159ms/step - loss: 1.1700
Epoch 12/30
460/460 [==============================] - 74s 159ms/step - lo

## Step 6: Generating text


In [135]:
model.save('fiction_gen_new.h5') 

In [136]:
from tensorflow.keras.models import load_model

In [137]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

model.load_weights('fiction_gen_new.h5')

model.build(tf.TensorShape([1, None]))


In [138]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (1, None, 64)             4800      
_________________________________________________________________
gru_5 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_5 (Dense)              (1, None, 75)             77025     
Total params: 3,443,001
Trainable params: 3,443,001
Non-trainable params: 0
_________________________________________________________________


In [139]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters. Similar to our work in the RNN
  time series problems.
  '''

  # Number of characters to generate
  num_generate = gen_size

  # Vecotrizing starting seed text
  input_eval = [char_to_ind[s] for s in start_seed]

  # Expand to match batch format shape
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty list to hold resulting generated text
  text_generated = []

  # Temperature effects randomness in our resulting text
  # The term is derived from entropy/thermodynamics.
  # The temperature is used to effect probability of next characters.
  # Higher probability == lesss surprising/ more expected
  # Lower temperature == more surprising / less expected
 
  temperature = temp

  # Here batch size == 1
  model.reset_states()

  for i in range(num_generate):

      # Generate Predictions
      predictions = model(input_eval)

      # Remove the batch shape dimension
      predictions = tf.squeeze(predictions, 0)

      # Use a cateogircal disitribution to select the next character
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # Pass the predicted charracter for the next input
      input_eval = tf.expand_dims([predicted_id], 0)

      # Transform back to character letter
      text_generated.append(ind_to_char[predicted_id])

  return (start_seed + ''.join(text_generated))

In [140]:
print(generate_text(model,"Time",gen_size=1000))

Time, when it
swung forward within an animal.

      Then they found it near me.

An hour later, sir, as is greater than all that Tardos Mors and
Mors Kajous felt for me to reach the comparatively so helpen a few more words
hung on and steal the other. Nevertheless, not 'the great white hole in monarcantly.  "I think we were turning dull"
  like nothing but tendency. It seems a sealed
vastne!

As I went to the course to the First Line from it.  They wanted to
know me about the preceding due depths in a dry human. "Iom the same
places in his provisions and down.  This in search of the master, in the night, but to
vicit was to remark the necessary palace of the Zodangan and of
all ten years he were
just got terrible eyes, a perfect cylinder must have flooded behind them along
the refraction, and I have constructed my way behind them.

It was not a bit for the last twentyfive million. The expesitor, as unknownwazed
and perhaps all knowledge and then we shall find him off in the nearest wa